{{- if .Values.wordpress.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "wordpress-mysql-chart.wpHpaName" . }}
  labels:
    {{- include "wordpress-mysql-chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "wordpress-mysql-chart.fullname" . }}
  minReplicas: {{ .Values.wordpress.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.wordpress.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.wordpress.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
