# For demo purposes : user=root & password=mysql-password (base64 encoded)
apiVersion: v1
kind: Secret
metadata:
  name: db-auth-secret
type: Opaque
data:
  user: {{ .Values.mysqlAdminUserBase64 | quote }}
  password: {{ .Values.mysqlAdminPassBase64 | quote }}
