name: Terraform provisioning

on:
  push:
    branches:
      - "main"
  release:
    types:
      - "published"

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZ_SUBID}}
      ARM_TENANT_ID: ${{secrets.AZ_TENANTID}}
      ARM_ACCESS_KEY: ${{secrets.TF_ARM_ACCESS_KEY}}

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: List terraform directory
        run: pwd &&  ls -a
      
      - name: Terraform init
        id: init
        run: terraform init
      
      - name: Terraform check
        id: validate
        run: terraform validate
      
      - name: Terraform plan
        id: plan
        run: terraform plan -var aks_sp_client_id=${{secrets.TF_ARM_CLIENT_ID}} -var aks_sp_client_secret=${{secrets.TF_ARM_CLIENT_SECRET}} -var mysql_admin_user=${{secrets.MYSQL_USER}} -var mysql_admin_password=${{secrets.MYSQL_PASS}}
      
      - name: Terraform apply
        if: github.event_name == 'release'
        id: apply
        run: terraform apply -auto-approve -var aks_sp_client_id=${{secrets.TF_ARM_CLIENT_ID}} -var aks_sp_client_secret=${{secrets.TF_ARM_CLIENT_SECRET}} -var mysql_admin_user=${{secrets.MYSQL_USER}} -var mysql_admin_password=${{secrets.MYSQL_PASS}}
